// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IVPwNo_gzhox_9p4z-82-OvG4Bwiv3E',
    appId: '1:1055398183314:web:8aa46a804c70e1677e814b',
    messagingSenderId: '1055398183314',
    projectId: 'barista-b0741',
    authDomain: 'barista-b0741.firebaseapp.com',
    storageBucket: 'barista-b0741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFKbdiBu93Uudhmc6beq1zxawn7exuJts',
    appId: '1:1055398183314:android:692a833d19942cd37e814b',
    messagingSenderId: '1055398183314',
    projectId: 'barista-b0741',
    storageBucket: 'barista-b0741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb802LCRzw9OkXErAkuRq3ikRokgfjrJ8',
    appId: '1:1055398183314:ios:2abf37a9304c35ad7e814b',
    messagingSenderId: '1055398183314',
    projectId: 'barista-b0741',
    storageBucket: 'barista-b0741.appspot.com',
    iosBundleId: 'com.GhTech.barista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb802LCRzw9OkXErAkuRq3ikRokgfjrJ8',
    appId: '1:1055398183314:ios:2abf37a9304c35ad7e814b',
    messagingSenderId: '1055398183314',
    projectId: 'barista-b0741',
    storageBucket: 'barista-b0741.appspot.com',
    iosBundleId: 'com.GhTech.barista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0IVPwNo_gzhox_9p4z-82-OvG4Bwiv3E',
    appId: '1:1055398183314:web:4de5f397aa0a28e77e814b',
    messagingSenderId: '1055398183314',
    projectId: 'barista-b0741',
    authDomain: 'barista-b0741.firebaseapp.com',
    storageBucket: 'barista-b0741.appspot.com',
  );
}
